title: Sistema de Processo Judicial
description: Documentação da arquitetura Domain-Driven Design
baseurl: "/projudi"
url: "https://joaopaulopresa.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .github/
  - package.json
  - package-lock.json
  - docusaurus.config.js
  - sidebars.js
  - blog/
  - docs/
  - src/
  - static/
  - build/

# Collections
collections:
  bounded_contexts:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "bounded_contexts"
    values:
      layout: "bounded_context"

# Navigation
nav_links:
  - title: "Início"
    url: "/"
  - title: "Contextos"
    url: "/contextos/"
  - title: "Shared Kernel"
    url: "/shared-kernel/"

# Theme settings
minima:
  social_links:
    github: joaopaulopresa